name: Tests

on:
  pull_request:
    branches: [ 'master' ]
  workflow_dispatch:	

jobs:
  build-and-test:
    strategy:
      fail-fast: false
      matrix:
        java: [ '17', '21' ]
        os: [ ubuntu-latest, macos-latest, windows-latest ]
        experimental: [ false ]
    runs-on: ${{ matrix.os }}
    continue-on-error: ${{ matrix.experimental }}
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    
    - name: Set up JDK ${{ matrix.java }}
      uses: actions/setup-java@v4
      with:
        java-version: ${{ matrix.java }}
        distribution: 'temurin'
        cache: 'maven'
      
    - name: Set up Maven
      uses: stCarolas/setup-maven@v5
      with:
        maven-version: '3.9.7'
        
    - name: Run Maven tests with a virtual display
      run: |
        xvfb-run mvn -V clean verify
